import { supabaseAdmin } from '../../utils/supabase.js';
import { logger } from '../../utils/logger.js';

export interface ReferralCode {
  id: string;
  user_id: string;
  code: string;
  created_at: string;
}

export interface Referral {
  id: string;
  referrer_id: string;
  referred_user_id: string;
  referral_code: string;
  status: 'pending' | 'completed' | 'cancelled';
  reward_amount_usd: number;
  reward_credited: boolean;
  reward_credited_at: string | null;
  reward_transaction_id: string | null;
  signup_ip_address: string | null;
  signup_user_agent: string | null;
  signup_device_fingerprint: string | null;
  created_at: string;
  completed_at: string | null;
}

export interface ReferralStats {
  total_referrals: number;
  pending_referrals: number;
  completed_referrals: number;
  total_earnings_usd: number;
  total_earnings_ngn: number;
}

export class ReferralService {
  /**
   * Get user's referral code
   */
  async getUserReferralCode(userId: string): Promise<ReferralCode | null> {
    try {
      const { data, error } = await supabaseAdmin
        .from('referral_codes')
        .select('*')
        .eq('user_id', userId)
        .single();

      if (error) {
        // If no code exists, generate one
        if (error.code === 'PGRST116') {
          return await this.generateReferralCode(userId);
        }
        throw error;
      }

      return data;
    } catch (error: any) {
      logger.error({ error, userId }, 'Failed to get referral code');
      throw new Error('Failed to get referral code');
    }
  }

  /**
   * Generate a new referral code for a user
   * (Usually auto-generated by trigger, but this is a fallback)
   */
  async generateReferralCode(userId: string): Promise<ReferralCode> {
    try {
      // Call the database function to generate a unique code
      const { data: code, error: codeError } = await supabaseAdmin
        .rpc('generate_referral_code');

      if (codeError) throw codeError;

      // Insert the code
      const { data, error } = await supabaseAdmin
        .from('referral_codes')
        .insert({
          user_id: userId,
          code: code as string,
        })
        .select()
        .single();

      if (error) throw error;

      logger.info({ userId, code }, 'Generated referral code');
      return data;
    } catch (error: any) {
      logger.error({ error, userId }, 'Failed to generate referral code');
      throw new Error('Failed to generate referral code');
    }
  }

  /**
   * Validate and apply a referral code during signup
   */
  async applyReferralCode(params: {
    referralCode: string;
    newUserId: string;
    ipAddress?: string;
    userAgent?: string;
    deviceFingerprint?: string;
  }): Promise<Referral> {
    const { referralCode, newUserId, ipAddress, userAgent, deviceFingerprint } = params;

    try {
      // 1. Find the referral code
      const { data: codeData, error: codeError } = await supabaseAdmin
        .from('referral_codes')
        .select('user_id')
        .eq('code', referralCode.toUpperCase())
        .single();

      if (codeError || !codeData) {
        throw new Error('Invalid referral code');
      }

      const referrerId = codeData.user_id;

      // 2. Prevent self-referral
      if (referrerId === newUserId) {
        throw new Error('Cannot refer yourself');
      }

      // 3. Check if user was already referred
      const { data: existingReferral } = await supabaseAdmin
        .from('referrals')
        .select('id')
        .eq('referred_user_id', newUserId)
        .single();

      if (existingReferral) {
        throw new Error('User already referred by someone else');
      }

      // 4. Fraud prevention: Check for suspicious patterns
      if (ipAddress) {
        const { data: recentReferrals, error: checkError } = await supabaseAdmin
          .from('referrals')
          .select('id')
          .eq('signup_ip_address', ipAddress)
          .gte('created_at', new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString());

        if (!checkError && recentReferrals && recentReferrals.length >= 3) {
          logger.warn({ ipAddress, count: recentReferrals.length }, 'Suspicious referral activity detected');
          // Don't throw error, but log for review
        }
      }

      // 5. Create referral record
      const { data: referral, error: referralError } = await supabaseAdmin
        .from('referrals')
        .insert({
          referrer_id: referrerId,
          referred_user_id: newUserId,
          referral_code: referralCode.toUpperCase(),
          status: 'pending',
          signup_ip_address: ipAddress || null,
          signup_user_agent: userAgent || null,
          signup_device_fingerprint: deviceFingerprint || null,
        })
        .select()
        .single();

      if (referralError) throw referralError;

      logger.info({
        referrerId,
        referredUserId: newUserId,
        referralCode,
      }, '✅ Referral code applied successfully');

      return referral;
    } catch (error: any) {
      logger.error({ error, referralCode, newUserId }, 'Failed to apply referral code');
      throw error;
    }
  }

  /**
   * Get referral statistics for a user
   */
  async getReferralStats(userId: string): Promise<ReferralStats> {
    try {
      // Get all referrals made by this user
      const { data: referrals, error } = await supabaseAdmin
        .from('referrals')
        .select('status, reward_amount_usd, reward_credited')
        .eq('referrer_id', userId);

      if (error) throw error;

      const stats: ReferralStats = {
        total_referrals: referrals?.length || 0,
        pending_referrals: referrals?.filter(r => r.status === 'pending').length || 0,
        completed_referrals: referrals?.filter(r => r.status === 'completed').length || 0,
        total_earnings_usd: referrals
          ?.filter(r => r.reward_credited)
          .reduce((sum, r) => sum + Number(r.reward_amount_usd), 0) || 0,
        total_earnings_ngn: 0, // Will be calculated from wallet_transactions
      };

      // Get total NGN earnings from wallet transactions
      const { data: transactions, error: txError } = await supabaseAdmin
        .from('wallet_transactions')
        .select('amount')
        .eq('user_id', userId)
        .eq('source', 'referral_bonus')
        .eq('type', 'credit');

      if (!txError && transactions) {
        // Sum up all referral bonus transactions (amount is in kobo)
        stats.total_earnings_ngn = transactions.reduce((sum, tx) => sum + Number(tx.amount), 0) / 100;
      }

      return stats;
    } catch (error: any) {
      logger.error({ error, userId }, 'Failed to get referral stats');
      throw new Error('Failed to get referral stats');
    }
  }

  /**
   * Get referral history for a user
   */
  async getReferralHistory(userId: string): Promise<Referral[]> {
    try {
      const { data, error } = await supabaseAdmin
        .from('referrals')
        .select('*')
        .eq('referrer_id', userId)
        .order('created_at', { ascending: false });

      if (error) throw error;

      return data || [];
    } catch (error: any) {
      logger.error({ error, userId }, 'Failed to get referral history');
      throw new Error('Failed to get referral history');
    }
  }

  /**
   * Manually credit a referral reward (admin function)
   */
  async creditReferralReward(referralId: string): Promise<string> {
    try {
      const { data, error } = await supabaseAdmin
        .rpc('credit_referral_reward', {
          p_referral_id: referralId,
          p_reward_amount_usd: 1.00,
        });

      if (error) throw error;

      logger.info({ referralId, transactionId: data }, '✅ Referral reward credited');
      return data as string;
    } catch (error: any) {
      logger.error({ error, referralId }, 'Failed to credit referral reward');
      throw error;
    }
  }

  /**
   * Cancel a referral (admin function)
   */
  async cancelReferral(referralId: string, reason: string): Promise<void> {
    try {
      const { error } = await supabaseAdmin
        .from('referrals')
        .update({
          status: 'cancelled',
        })
        .eq('id', referralId);

      if (error) throw error;

      logger.info({ referralId, reason }, 'Referral cancelled');
    } catch (error: any) {
      logger.error({ error, referralId }, 'Failed to cancel referral');
      throw error;
    }
  }

  /**
   * Get referral link for a user
   */
  getReferralLink(referralCode: string, baseUrl: string = 'https://solpay.app'): string {
    return `${baseUrl}?ref=${referralCode}`;
  }
}

export const referralService = new ReferralService();

